[workspace]
members = ["xtask", "firewall", "firewall-common", "controller", "message"]
resolver = "2"

[workspace.dependencies]
netp = { git = "https://github.com/AOx0/netp-1", version = "0.1.0" }
bstr = "1.10.0"
async-bincode = "0.7.2"
futures = "0.3.30"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128" }
schemars = { version = "0.8.21" }
