name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - run: npm install -g tailwindcss
      - name: Install just
        uses: baptiste0928/cargo-install@v3
        with:
          crate: just
          locked: true
      - name: Install bpf-linker
        uses: baptiste0928/cargo-install@v3
        with:
          crate: bpf-linker
          locked: true
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          locked: true
      - run: just build
      - run: cargo nextest run --verbose
