name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - name: Install Tailwind CSS
        run: |
          wget https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.15/tailwindcss-linux-x64 -O /usr/local/bin/tailwindcss
          chmod +x /usr/local/bin/tailwindcss
      - name: Install just
        uses: baptiste0928/cargo-install@v3
        with:
          crate: just
      - name: Install bpf-linker
        uses: baptiste0928/cargo-install@v3
        with:
          crate: bpf-linker
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-nextest
      - run: just build
      - run: cargo nextest run
